# Configurations de base
baseurl: "http://williambertrand.ca/"
#baseurl: "" # Commentez la ligne ci-dessus et décommentez celle-ci pour tester le site localement
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# Configurations de l'interface utilisateur
title: "Photographie par William Bertrand"
subtitle: "Découvrez le monde à travers mon objectif !"
author: "William Bertrand"
header:
 title: "Photographie"
 subtitle: "par William Bertrand"
footer:
 name: "Bonjour, je m'appelle William"
 bio: "Je suis photographe passionné, capturant des moments uniques à travers mon objectif. Explorez mon travail et découvrez le monde à travers mes yeux."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  # twitter: "https://www.twitter.com/williambertrand"
  instagram: "https://www.instagram.com/frozerty_"
  # dribbble: "https://dribbble.com/williambertrand"
  # linkedin: "https://www.linkedin.com/in/williambertrand"
  # github: "https://www.github.com/williambertrand"
  vsco: "https://vsco.co/willibert"
